export const AI_STRINGS={
  "vi": {
    "masterToggle": "Cải thiện ảnh thông minh bằng AI",
    "toggle": "Xoá phông và ánh sáng chân dung",
    "detailToggle": "Làm nét ảnh",
    "detailHint": "Khử nhiễu và tăng nét bằng AI trước Styles. Ảnh HDR và HEIC chưa được hỗ trợ.",


    "detailApplied": "Đã làm nét bằng AI trước khi tạo Styles.",
    "detailPreparing": "Đang chuẩn bị model làm nét AI…",
    "detailWorking": "Đang phục hồi và làm nét ảnh bằng AI…",
    "detailSkipped": "Đã giữ ảnh gốc vì không thể chạy AI làm nét:",
    "detailHeic": "HEIC hiện được giữ nguyên để bảo toàn HDR, Styles và Portrait; AI làm nét chưa hỗ trợ trực tiếp HEIC.",
    "settings": "Tuỳ chọn AI",
    "model": "Model",
    "modelHint": "Mức Lite, Standard hoặc Pro áp dụng cho mọi tính năng AI đang bật. Chỉ tải model cần thiết khi xử lý.",
    "cleanup": "Dọn bộ nhớ",
    "cleanupHint": "Xoá dữ liệu công cụ đã tải; giữ ảnh và lựa chọn của bạn. Công cụ sẽ tải lại khi cần.",
    "cleaning": "Đang dọn dữ liệu…",
    "cleaned": "Đã dọn dữ liệu tải về.",
    "cleanupFailed": "Chưa dọn hết dữ liệu. Hãy thử lại.",
    "acceleration": "Tăng tốc GPU",
    "accelerationHint": "Bật: GPU · Tắt: CPU. Áp dụng cho ảnh tiếp theo.",
    "inferenceCpu": "Đang tạo độ sâu trên CPU",
    "hint": "Thêm Portrait để chỉnh ƒ và ánh sáng trong Ảnh. Giữ depth gốc nếu đã có.",
    "loading": "Đang chuẩn bị AI",
    "download": "Đang tải AI",
    "modelLoading": "Đang chuẩn bị AI",
    "refining": "Đang tinh chỉnh viền độ sâu",
    "qualityFallback": "Đang chọn mức chất lượng phù hợp với thiết bị",
    "inference": "Đang tạo độ sâu trên GPU",
    "encoding": "Đang thêm Portrait vào HEIC",
    "skip": "Đã giữ depth và Portrait gốc.",
    "compatibility": "Đã giữ Styles gốc. Định dạng mới này chưa được kiểm chứng với Portrait AI và Soft Skin bổ sung.",
    "ready": "Portrait mặc định tắt. Sau khi lưu, mở ảnh trong Ảnh và bật Portrait để chỉnh ƒ và ánh sáng.",
    "failed": "AI chưa xử lý được. Bản Styles bình thường vẫn có thể tải xuống.",
    "failureStage": "Bước bị lỗi",
    "gpu": "Trình duyệt chưa hỗ trợ WebGPU. Bản Styles bình thường vẫn có thể tải xuống.",
    "cancel": "Dừng AI",
    "cancelled": "Đã dừng AI. Bản Styles vẫn có thể tải xuống.",
    "timeout": "AI mất quá lâu. Hãy thử lại hoặc tải bản Styles.",
    "preview": "Chân dung",
    "focus": "Chạm để lấy nét",
    "blur": "Độ mờ",
    "aperture": "Khẩu độ",
    "reset": "Đặt lại lấy nét và độ mờ",
    "focusKeyboard": "Chọn điểm lấy nét. Dùng phím mũi tên để di chuyển, Enter để lấy nét ở giữa.",
    "updating": "Đang cập nhật bản tải xuống…",
    "updateFailed": "Chưa cập nhật được. Hãy thử đặt lại lấy nét.",
    "previewFailed": "Không hiển thị được preview. Bạn vẫn có thể chỉnh Portrait trong Ảnh."
  },
  "en": {
    "masterToggle": "Smart Enhance photo with AI",
    "toggle": "Depth Effect with Portrait Lighting",
    "detailToggle": "Sharpen Photo",
    "detailHint": "AI restoration before Styles. HDR and existing HEIC sources are not yet supported.",


    "detailApplied": "AI sharpening applied before Styles.",
    "detailPreparing": "Preparing AI detail model…",
    "detailWorking": "Restoring and sharpening with AI…",
    "detailSkipped": "Original retained because AI detail could not run:",
    "detailHeic": "HEIC is preserved to protect HDR, Styles and Portrait; direct HEIC sharpening is not yet supported.",
    "settings": "AI settings",
    "model": "Model",
    "modelHint": "Lite, Standard or Pro applies to all enabled AI effects. Downloads only required models when processing.",
    "cleanup": "Clear cache",
    "cleanupHint": "Removes downloaded tools; keeps photos and preferences. Tools download again when needed.",
    "cleaning": "Clearing downloaded tools…",
    "cleaned": "Downloaded tools cleared.",
    "cleanupFailed": "Could not clear all data. Please retry.",
    "acceleration": "GPU acceleration",
    "accelerationHint": "On: GPU · Off: CPU. Applies to the next photo.",
    "inferenceCpu": "Generating depth on CPU",
    "hint": "Add Portrait to edit aperture and lighting in Photos. Existing depth is preserved.",
    "loading": "Preparing AI",
    "download": "Downloading AI",
    "modelLoading": "Preparing AI",
    "refining": "Refining depth edges",
    "qualityFallback": "Choosing a quality level for this device",
    "inference": "Generating depth on GPU",
    "encoding": "Adding Portrait to HEIC",
    "skip": "Original depth and Portrait preserved.",
    "compatibility": "Original Styles preserved. This newer format is not yet verified for AI Portrait or added Soft Skin.",
    "ready": "Portrait starts off. After saving, open the photo in Photos and turn on Portrait to adjust aperture and lighting.",
    "failed": "AI could not finish. Your normal Styles photo is still available.",
    "failureStage": "Failed step",
    "gpu": "WebGPU is unavailable. Your normal Styles photo is still available.",
    "cancel": "Stop AI",
    "cancelled": "AI stopped. Your Styles photo is still available.",
    "timeout": "AI took too long. Retry, or download your Styles photo.",
    "preview": "Portrait",
    "focus": "Tap to focus",
    "blur": "Blur",
    "aperture": "Aperture",
    "reset": "Reset focus and blur",
    "focusKeyboard": "Choose a focus point. Use arrow keys to move, or Enter to focus at the centre.",
    "updating": "Updating your download…",
    "updateFailed": "Could not update. Try resetting the focus.",
    "previewFailed": "Preview unavailable. You can still edit Portrait in Photos."
  },
  "zh": {
    "masterToggle": "使用 AI 增强照片",
    "toggle": "AI 景深效果",
    "detailToggle": "照片锐化",
    "detailHint": "在添加风格前使用 AI 修复细节。暂不支持 HDR 和原始 HEIC 图片。",


    "detailApplied": "已在创建摄影风格前完成 AI 锐化。",
    "detailPreparing": "正在准备 AI 锐化模型…",
    "detailWorking": "正在使用 AI 修复与锐化照片…",
    "detailSkipped": "AI 细节处理不可用，已保留原图：",
    "detailHeic": "为保护 HDR、风格和人像数据，暂时保留原始 HEIC；尚不支持直接锐化 HEIC。",
    "settings": "AI 设置",
    "model": "模型",
    "modelHint": "Lite、Standard 或 Pro 应用于所有启用的 AI 功能，仅在处理时下载所需模型。",
    "cleanup": "清理缓存",
    "cleanupHint": "删除已下载的工具，保留照片和偏好设置。需要时会重新下载工具。",
    "cleaning": "正在清理下载数据…",
    "cleaned": "已清理下载的工具。",
    "cleanupFailed": "未能清理全部数据，请重试。",
    "acceleration": "GPU 加速",
    "accelerationHint": "开启：GPU · 关闭：CPU。适用于下一张照片；预览仍使用 GPU。",
    "inferenceCpu": "CPU 正在生成深度",
    "hint": "添加人像，在照片 App 中调整光圈和人像光效。保留原有深度，AI 在设备上运行。",
    "loading": "正在准备 AI",
    "download": "正在下载 AI",
    "modelLoading": "正在准备 AI",
    "refining": "正在优化深度边缘",
    "qualityFallback": "正在选择适合此设备的画质",
    "inference": "GPU 正在生成深度",
    "encoding": "正在为 HEIC 添加人像",
    "skip": "已保留原始深度和人像。",
    "compatibility": "已保留原始风格。此新格式尚未验证 AI 人像和补充柔肤功能。",
    "ready": "人像默认关闭。保存后在照片 App 中开启人像，调整光圈和人像光效。",
    "failed": "AI 未能完成，仍可下载普通风格照片。",
    "failureStage": "失败步骤",
    "gpu": "浏览器不支持 WebGPU，仍可下载普通风格照片。",
    "cancel": "停止 AI",
    "cancelled": "AI 已停止，仍可下载风格照片。",
    "timeout": "AI 处理超时，可重试或下载风格照片。",
    "preview": "人像",
    "focus": "轻点对焦",
    "blur": "虚化",
    "aperture": "光圈",
    "reset": "重置焦点与虚化",
    "focusKeyboard": "选择焦点。使用方向键移动，或按回车键对焦到中央。",
    "updating": "正在更新下载文件…",
    "updateFailed": "无法更新，请尝试重置焦点。",
    "previewFailed": "无法预览，仍可在照片 App 中调整人像。"
  }
};
