export const AI_STRINGS={
  "vi": {
    "toggle": "Độ sâu thông minh · ML",
    "hint": "Thêm Portrait để chỉnh ƒ và ánh sáng trong Ảnh. Giữ depth gốc nếu đã có. AI chạy trên thiết bị.",
    "loading": "Đang tải AI · khoảng 120 MB lần đầu",
    "download": "Đang tải AI",
    "modelLoading": "Đang chuẩn bị AI",
    "refining": "Đang tinh chỉnh viền độ sâu",
    "qualityFallback": "Đang chọn mức chất lượng phù hợp với thiết bị",
    "inference": "Đang tạo độ sâu trên GPU",
    "encoding": "Đang thêm Portrait vào HEIC",
    "skip": "Đã giữ depth và Portrait gốc.",
    "compatibility": "Đã giữ Styles gốc. Định dạng mới này chưa được kiểm chứng với Portrait AI và Soft Skin bổ sung.",
    "ready": "Portrait mặc định tắt. Sau khi lưu, mở ảnh trong Ảnh và bật Portrait để chỉnh ƒ và ánh sáng.",
    "failed": "AI chưa xử lý được. Bản Styles bình thường vẫn có thể tải xuống.",
    "gpu": "Trình duyệt chưa hỗ trợ WebGPU. Bản Styles bình thường vẫn có thể tải xuống.",
    "cancel": "Dừng AI",
    "cancelled": "Đã dừng AI. Bản Styles vẫn có thể tải xuống.",
    "timeout": "AI mất quá lâu. Hãy thử lại hoặc tải bản Styles.",
    "preview": "Xem trước xoá phông",
    "focus": "Chạm vào ảnh để chọn điểm lấy nét.",
    "blur": "Độ mờ xem trước",
    "reset": "Đặt lại lấy nét và độ mờ",
    "focusKeyboard": "Chọn điểm lấy nét. Dùng phím mũi tên để di chuyển, Enter để lấy nét ở giữa.",
    "updating": "Đang cập nhật bản tải xuống…",
    "updateFailed": "Chưa cập nhật được. Hãy thử đặt lại lấy nét.",
    "previewFailed": "Không hiển thị được preview. Bạn vẫn có thể chỉnh Portrait trong Ảnh."
  },
  "en": {
    "toggle": "Intelligent Depth · ML",
    "hint": "Add Portrait to edit aperture and lighting in Photos. Existing depth is preserved. AI runs on your device.",
    "loading": "Loading AI · about 120 MB initially",
    "download": "Downloading AI",
    "modelLoading": "Preparing AI",
    "refining": "Refining depth edges",
    "qualityFallback": "Choosing a quality level for this device",
    "inference": "Generating depth on GPU",
    "encoding": "Adding Portrait to HEIC",
    "skip": "Original depth and Portrait preserved.",
    "compatibility": "Original Styles preserved. This newer format is not yet verified for AI Portrait or added Soft Skin.",
    "ready": "Portrait starts off. After saving, open the photo in Photos and turn on Portrait to adjust aperture and lighting.",
    "failed": "AI could not finish. Your normal Styles photo is still available.",
    "gpu": "WebGPU is unavailable. Your normal Styles photo is still available.",
    "cancel": "Stop AI",
    "cancelled": "AI stopped. Your Styles photo is still available.",
    "timeout": "AI took too long. Retry, or download your Styles photo.",
    "preview": "Background blur preview",
    "focus": "Tap the photo to choose a focus point.",
    "blur": "Preview blur",
    "reset": "Reset focus and blur",
    "focusKeyboard": "Choose a focus point. Use arrow keys to move, or Enter to focus at the centre.",
    "updating": "Updating your download…",
    "updateFailed": "Could not update. Try resetting the focus.",
    "previewFailed": "Preview unavailable. You can still edit Portrait in Photos."
  },
  "zh": {
    "toggle": "智能景深 · ML",
    "hint": "添加人像，在照片 App 中调整光圈和人像光效。保留原有深度，AI 在设备上运行。",
    "loading": "正在加载 AI · 首次约 120 MB",
    "download": "正在下载 AI",
    "modelLoading": "正在准备 AI",
    "refining": "正在优化深度边缘",
    "qualityFallback": "正在选择适合此设备的画质",
    "inference": "GPU 正在生成深度",
    "encoding": "正在为 HEIC 添加人像",
    "skip": "已保留原始深度和人像。",
    "compatibility": "已保留原始风格。此新格式尚未验证 AI 人像和补充柔肤功能。",
    "ready": "人像默认关闭。保存后在照片 App 中开启人像，调整光圈和人像光效。",
    "failed": "AI 未能完成，仍可下载普通风格照片。",
    "gpu": "浏览器不支持 WebGPU，仍可下载普通风格照片。",
    "cancel": "停止 AI",
    "cancelled": "AI 已停止，仍可下载风格照片。",
    "timeout": "AI 处理超时，可重试或下载风格照片。",
    "preview": "背景虚化预览",
    "focus": "点击照片选择焦点。",
    "blur": "预览虚化程度",
    "reset": "重置焦点与虚化",
    "focusKeyboard": "选择焦点。使用方向键移动，或按回车键对焦到中央。",
    "updating": "正在更新下载文件…",
    "updateFailed": "无法更新，请尝试重置焦点。",
    "previewFailed": "无法预览，仍可在照片 App 中调整人像。"
  }
};
